In [10]:
import requests
import lxml.html as lh
import pandas as pd

In [11]:
url='https://www.payscale.com/data/gender-pay-gap'

In [12]:
tables = pd.read_html(url)
html = tables[0]

In [13]:

html = html.copy()

In [14]:
new_header = html.iloc[0] #grab the first row for the header
html = html[1:] #take the data less the header row
html.columns = new_header #set the header row as the df header

In [15]:
#clean up the dollar signs and percent signs
html['Uncontrolled Gender Pay Gap'] = html['Uncontrolled Gender Pay Gap'].replace({'\$':''}, regex = True)
html['Controlled Gender Pay Gap'] = html['Controlled Gender Pay Gap'].replace({'\$':''}, regex = True)
html['Percent Men (BLS)'] = html['Percent Men (BLS)'].replace({'\%':''}, regex = True)
html['Percent Women (BLS)'] = html['Percent Women (BLS)'].replace({'\%':''}, regex = True)
html

,Occupation,Uncontrolled Gender Pay Gap,Controlled Gender Pay Gap,Percent Men (BLS),Percent Women (BLS)
1,Architecture & Engineering,0.93,0.99,84,16
2,"Arts, Design, Entertainment, Sports & Media",0.93,0.98,53,47
3,Building & Grounds Cleaning & Maintenance,0.79,0.98,59,41
4,Business & Financial Operations,0.86,0.97,46,54
5,Community & Social Services,0.96,1.00,34,67
6,Computer & Mathematical,0.92,0.98,74,26
7,Construction & Extraction,0.88,0.96,97,3
8,"Education, Training & Library",0.73,0.97,27,73
9,"Farming, Fishing & Forestry",0.78,0.95,76,24
10,Food Preparation & Serving Related,0.87,0.97,45,56
11,Healthcare Practitioners & Technical,0.89,0.98,25,75
12,Healthcare Support,0.96,0.98,13,87
13,"Installation, Maintenance & Repair",0.87,0.94,96,4
14,Legal,0.62,0.98,48,52
15,"Life, Physical & Social Science",0.93,0.98,53,47
16,Management,0.77,0.97,60,40
17,Office & Administrative Support,0.94,0.98,28,72
18,Personal Care & Service,0.90,0.97,23,77
19,Production,0.84,0.96,71,29
20,Protective Service,0.86,0.98,78,23
21,Sales & Related,0.80,0.96,51,49
22,Transportation & Material Moving,0.84,0.97,82,18

In [16]:
html.to_csv('C:/Users/ca25935/Desktop/UCD Data Analytics/Homework/ETL project/data/cleaned/CSVs/ETLproject/data cleaned/payscale_data.csv')